// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PX3lrwVl8k1NiAVPT5fsxp6nbY4AItg',
    appId: '1:610133243054:web:4cf1390fa7140fd9b7293f',
    messagingSenderId: '610133243054',
    projectId: 'enhance-e1b85',
    authDomain: 'enhance-e1b85.firebaseapp.com',
    storageBucket: 'enhance-e1b85.firebasestorage.app',
    measurementId: 'G-LTTKMGVZLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5RE11CDbhZwfNhDCQi27lFZFCPSa9ak',
    appId: '1:610133243054:android:d4e5e84140cb269ab7293f',
    messagingSenderId: '610133243054',
    projectId: 'enhance-e1b85',
    storageBucket: 'enhance-e1b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNLw4V1q-iHK3uRCKP5H67Ofm55O5kXc',
    appId: '1:610133243054:ios:fd8e4c9e0f050962b7293f',
    messagingSenderId: '610133243054',
    projectId: 'enhance-e1b85',
    storageBucket: 'enhance-e1b85.firebasestorage.app',
    iosBundleId: 'com.example.gymai3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcNLw4V1q-iHK3uRCKP5H67Ofm55O5kXc',
    appId: '1:610133243054:ios:c3f80b5cd5bc6ceab7293f',
    messagingSenderId: '610133243054',
    projectId: 'enhance-e1b85',
    storageBucket: 'enhance-e1b85.firebasestorage.app',
    iosBundleId: 'com.example.gymai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0PX3lrwVl8k1NiAVPT5fsxp6nbY4AItg',
    appId: '1:610133243054:web:90f886f15480f16bb7293f',
    messagingSenderId: '610133243054',
    projectId: 'enhance-e1b85',
    authDomain: 'enhance-e1b85.firebaseapp.com',
    storageBucket: 'enhance-e1b85.firebasestorage.app',
    measurementId: 'G-R25E04RPST',
  );
}
